# Generated by Django 5.2.12 on 2026-04-22 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentresult",
            name="job_description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
